const factonStates: string[] = [
  'Blight',
  'Boom',
  'Bust',
  'Civil Liberty',
  'Civil Unrest',
  'Civil War',
  'Cold War',
  'Colonisation',
  'Damaged',
  'Drought',
  'Election',
  'Expansion',
  'Famine',
  'Historic Event',
  'Infrastructure Failure',
  'Investment',
  'Lockdown',
  'Natural Disaster',
  'None',
  'Outbreak',
  'Pirate Attack',
  'Public Holiday',
  'Retreat',
  'Revolution',
  'Technological Leap',
  'Terrorist Attack',
  'Trade War',
  'Under Attack',
  'Under Repairs',
  'War',
];

export default factonStates;
