const modules: string[] = [
  '1I Detailed Surface Scanner',
  '5D Fighter Hangar',
  '6D Fighter Hangar',
  '7D Fighter Hangar',
  '2A Frame Shift Drive',
  '2B Frame Shift Drive',
  '2C Frame Shift Drive',
  '2D Frame Shift Drive',
  '2E Frame Shift Drive',
  '3A Frame Shift Drive',
  '3B Frame Shift Drive',
  '3C Frame Shift Drive',
  '3D Frame Shift Drive',
  '3E Frame Shift Drive',
  '4A Frame Shift Drive',
  '4B Frame Shift Drive',
  '4C Frame Shift Drive',
  '4D Frame Shift Drive',
  '4E Frame Shift Drive',
  '5A Frame Shift Drive',
  '5B Frame Shift Drive',
  '5C Frame Shift Drive',
  '5D Frame Shift Drive',
  '5E Frame Shift Drive',
  '6A Frame Shift Drive',
  '6B Frame Shift Drive',
  '6C Frame Shift Drive',
  '6D Frame Shift Drive',
  '6E Frame Shift Drive',
  '0A Kill Warrant Scanner',
  '0B Kill Warrant Scanner',
  '0C Kill Warrant Scanner',
  '0D Kill Warrant Scanner',
  '0E Kill Warrant Scanner',
  '1E Supercruise Assist',
];

export default modules;
