const ships: string[] = [
  'Adder',
  'Alliance Challenger',
  'Alliance Chieftain',
  'Alliance Crusader',
  'Anaconda',
  'Asp Explorer',
  'Asp Scout',
  'Beluga Liner',
  'Cobra MkIII',
  'Cobra MkIV',
  'Diamondback Explorer',
  'Diamondback Scout',
  'Dolphin',
  'Eagle MkII',
  'Federal Assault Ship',
  'Federal Corvette',
  'Federal Dropship',
  'Federal Gunship',
  'Fer-de-Lance',
  'Hauler',
  'Imperial Clipper',
  'Imperial Courier',
  'Imperial Cutter',
  'Imperial Eagle',
  'Keelback',
  'Krait MkII',
  'Krait Phantom',
  'Mamba',
  'Orca',
  'Python',
  'Sidewinder MkI',
  'Type-6 Transporter',
  'Type-7 Transporter',
  'Type-9 Heavy',
  'Type-10 Defender',
  'Viper MkIII',
  'Viper MkIV',
  'Vulture',
];

export default ships;
